version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - echo Build started on `date`
      - npm ci
      - npm run typecheck
      - npm run coverage
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: blaster-$(date +%Y-%m-%d)
